Repository SberTechJavaSchool/Homework, pull requests merged in 2018-03, with the labels that each got.

#110 03.1/03.2 Drozdov G
  hw02/src/ru/sberbank/homework/drozdov/Calculator.java
  hw03/src/ru/sberbank/homework/drozdov/Main.java
  hw03/src/ru/sberbank/homework/drozdov/URLReader.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/AccountIsLockedException.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/AmountNotValidException.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/Interaction.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/MainTerminal.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/NotEnoughMoneyException.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/PinValidator.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/Terminal.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/TerminalImpl.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/TerminalServer.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_1/WrongPinException.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_2/Main.java
  hw03/src/ru/sberbank/homework/drozdov/hw3_2/URLReader.java
Labels: bug

#117 09. Dergun
  hw09/pom.xml
  hw09/src/main/java/Termianl/MoneyValidator.java
  hw09/src/main/java/Termianl/PinStorage.java
  hw09/src/main/java/Termianl/PinValidator.java
  hw09/src/main/java/Termianl/Terminal.java
  hw09/src/main/java/Termianl/TerminalImpl.java
  hw09/src/main/java/Termianl/TerminalServer.java
  hw09/src/main/java/Termianl/exeptions/AccountIsLockedException.java
  hw09/src/main/java/Termianl/exeptions/InsufficientFundsExeption.java
  hw09/src/main/java/Termianl/exeptions/LoggedExeption.java
  hw09/src/main/java/Termianl/exeptions/NetworkConnectionExeption.java
  hw09/src/main/java/Termianl/exeptions/NotCorrectPinExeption.java
  hw09/src/main/java/Termianl/exeptions/ValidateMoneyExeption.java
  hw09/src/main/java/Termianl/exeptions/ValidatePinExeption.java
  hw09/src/test/java/Termianl/TerminalImplTest.java
  hw09/src/test/java/Termianl/TerminalServerTest.java
Labels: bug, waiting for review

#118 09. Кашин ДС
  hw09/META-INF/MANIFEST.MF
  hw09/pom.xml
  hw09/src/main/java/terminal/MainTerminal.java
  hw09/src/main/java/terminal/exception/AccountIsLockedException.java
  hw09/src/main/java/terminal/exception/NotAuthorizedException.java
  hw09/src/main/java/terminal/exception/NotEnoughMoneyException.java
  hw09/src/main/java/terminal/exception/NumberException.java
  hw09/src/main/java/terminal/exception/ServerProblemException.java
  hw09/src/main/java/terminal/model/Account.java
  hw09/src/main/java/terminal/model/AccountImpl.java
  hw09/src/main/java/terminal/model/PinValidator.java
  hw09/src/main/java/terminal/model/PinValidatorImpl.java
  hw09/src/main/java/terminal/model/Terminal.java
  hw09/src/main/java/terminal/model/TerminalImpl.java
  hw09/src/main/java/terminal/model/TerminalServer.java
  hw09/src/main/java/terminal/model/TerminalServerImpl.java
  hw09/src/main/java/terminal/writer/ConsoleWriter.java
  hw09/src/main/java/terminal/writer/Writer.java
  hw09/src/test/java/terminal/MainTerminalTest.java
  hw09/src/test/java/terminal/model/AccountImplTest.java
  hw09/src/test/java/terminal/model/PinValidatorImplTest.java
  hw09/src/test/java/terminal/model/TerminalImplTest.java
  hw09/src/test/java/terminal/model/TerminalServerImplTest.java
Labels: waiting for review

#84 03.1 Кудрявых
  hw03/src/ru/sberbank/homework/kudryavykh/Account.java
  hw03/src/ru/sberbank/homework/kudryavykh/Main.java
  hw03/src/ru/sberbank/homework/kudryavykh/MessageTerminal.java
  hw03/src/ru/sberbank/homework/kudryavykh/MessageTermnalInterface.java
  hw03/src/ru/sberbank/homework/kudryavykh/PinValidator.java
  hw03/src/ru/sberbank/homework/kudryavykh/Terminal.java
  hw03/src/ru/sberbank/homework/kudryavykh/TerminalImpl.java
  hw03/src/ru/sberbank/homework/kudryavykh/TerminalServer.java
Labels: bug

#104 09 Киселева
  hw09/pom.xml
  hw09/src/main/java/ru/sberbank/homework/kiseleva/Main.java
  hw09/src/main/java/ru/sberbank/homework/kiseleva/PinValidator.java
  hw09/src/main/java/ru/sberbank/homework/kiseleva/TerminalClient.java
  hw09/src/main/java/ru/sberbank/homework/kiseleva/TerminalImpl.java
  hw09/src/main/java/ru/sberbank/homework/kiseleva/TerminalServer.java
  hw09/src/main/java/ru/sberbank/homework/kiseleva/exceptions/AccountIsLockedException.java
  hw09/src/main/java/ru/sberbank/homework/kiseleva/exceptions/NotEnoughMoneyException.java
  hw09/src/main/java/ru/sberbank/homework/kiseleva/interfaces/Terminal.java
  hw09/src/test/java/ru/sberbank/homework/kiseleva/TerminalImplTest.java
  hw09/src/test/java/ru/sberbank/homework/kiseleva/TerminalServerTest.java
Labels: bug

#167 10 Андреев ЮИ
  hw10/build.gradle
  hw10/settings.gradle
  hw10/src/main/java/ru/sberbank/homework/andreev/task_01/AnnotationFinderApp.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_01/ClassesFromPackageProvider.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_02/ReflectionFieldCopier.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/CacheHandler.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/CacheProxy.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/CacheProxyBuilder.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/annotation/Cache.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/annotation/CacheType.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/annotation/Empty.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/annotation/Zip.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/cache/CacheParameterProcessor.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/cache/CacheProvider.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/cache/CacheProxyException.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/cache/FileCacheProvider.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/cache/InMemoryCacheProvider.java
  hw10/src/main/java/ru/sberbank/homework/andreev/task_03/cache/MethodParameterAnalyzer.java
  hw10/src/main/java/ru/sberbank/homework/common/BeanFieldCopier.java
  hw10/src/main/java/ru/sberbank/homework/common/annotation/ExperimentalFeature.java
  hw10/src/main/java/ru/sberbank/homework/common/annotation/Prototype.java
  hw10/src/main/java/ru/sberbank/homework/common/entity/Car.java
  hw10/src/main/java/ru/sberbank/homework/common/entity/TeslaModel3.java
  hw10/src/main/java/ru/sberbank/homework/common/entity/TeslaModelHydro.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_01/AnnotationFinderAppTest.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_02/ReflectionFieldCopierTest.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_02/objects/First.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_02/objects/TrimFirst.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/CacheProxyTest.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/method_classes/ForIdentityCheck.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/method_classes/ForIdentityCheckImpl.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/method_classes/ForSerializationSubObject.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/method_classes/IMethodClass.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/method_classes/MethodClass.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/method_classes/WithInternalParameter.java
  hw10/src/test/java/ru/sberbank/homework/andreev/task_03/method_classes/WithInternalParameterImpl.java
Labels: waiting for review

#165 02 Бобров ДС
  hw02/src/main/java/ru/sberbank/homework/bobrov/CalcImpl.java
  hw02/src/main/java/ru/sberbank/homework/bobrov/Main.java
  hw02/src/main/java/ru/sberbank/homework/bobrov/Parser.java
  hw02/src/main/java/ru/sberbank/homework/bobrov/oper/Add.java
  hw02/src/main/java/ru/sberbank/homework/bobrov/oper/Div.java
  hw02/src/main/java/ru/sberbank/homework/bobrov/oper/Multipl.java
  hw02/src/main/java/ru/sberbank/homework/bobrov/oper/Operation.java
  hw02/src/main/java/ru/sberbank/homework/bobrov/oper/Subtract.java
Labels: waiting for review
